### ISSUE TITLE
Replace `console.log` with `debug`

### ISSUE THREAD

**Issue by jackharrhy** [masoudz88/food_donations_frontend#3]
Without the application is many calls to `console.log`, but:
- they are visible all the time, even if you were to make a release build of the application
- there is no indication where the log is coming from, if it prints `here` to the console, you have to go find where that is, and if you have multiple calls to `console.log('here');`, good luck finding which one it is!

However, debugging at times is useful, and removing all of the console.logs might remove some insight to what the application is doing, so instead using [debug](https://www.npmjs.com/package/debug) would be better, so you can:
- namespace the debugs so you know which files the debugs are coming from
- don't show them by default, you can toggle them on or off so normal users don't see logs they don't need to

**Comment by masoudz88** [comment]
I am trying to use debug, I am still not sure how to do it but I am working on it
